x-compritas-template: &compritas-service
  image: ghcr.io/joselo/compritas:master
  pull_policy: always
  networks:
    - internal
  volumes:
    - storage:/app/storage
  restart: always
  environment:
    - SECRET_KEY_BASE
    - PHX_HOST
    - DATABASE_URL
    - FROM_EMAIL
    - STORAGE_PATH
    - RESEND_API_KEY
    - SMTP_SERVER
    - SMTP_PORT
    - SMTP_USERNAME
    - SMTP_PASSWORD
  healthcheck:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/up"]
    interval: 10s
    timeout: 5s
    retries: 3
    start_period: 30s
  expose:
    - "4000"
  extra_hosts:
    - "host.docker.internal:host-gateway"


services:
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    restart: unless-stopped
    environment:
      - PHX_HOST
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal

  compritas-blue:
    <<: *compritas-service
    container_name: compritas-blue

  compritas-green:
    <<: *compritas-service
    container_name: compritas-green

networks:
  internal:

volumes:
  caddy_data:
  caddy_config:
  storage:

